version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    environment:
      - PORT=8000
      - SECRET_KEY=change-this-in-production
    restart: unless-stopped